Increment 13
vstebletsov89/go-developer-course-shortener pull request #13
Opened 2022-03-10 09:40 UTC by vstebletsov89

2022-03-11 07:10 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +	userID := ctx.(string)
наверное можно в одну строку.  Но вообще кастуй типы с осторожностью, вдруг там не string. Откровенно говоря у меня ребята на проекте уже стреляли таким образом в ногу когда jwt токен обрабатывали) Хотя в текущем контексте можно сказать все ок, однако лучше подумать тогда над неймингом ctx
```suggestion
	userID, ok  := r.Context().Value(middleware.UserCtx).(string) 
```

2022-03-11 07:17 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
>  	shortURL := utils.MakeShortURL(h.config.BaseURL, id)
Наблюдаю копипаст бизнес логики, можем вынести в отдельную функцию или сделаем слой приложения (сервиса).

2022-03-11 07:18 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
>  	shortURL := utils.MakeShortURL(h.config.BaseURL, id)
Выше уже написал про копипаст)

2022-03-11 07:20 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +			http.Error(w, err.Error(), http.StatusBadRequest)
Я может что-то не учел, но скорее всего тут должен быть http.InternalServerError? Или я не прав?

2022-03-11 07:30 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +		}
Если не ошибаюсь, то здесь можно избавиться от вложенности, как то так. если err == nil то errors.As(err, &pgError) должно быть false.
```
if errors.As(err, &pgError) && pgError.Code == pgerrcode.UniqueViolation {
			id, err = h.storage.GetShortURLByOriginalURL(longURL)
			if err != nil {
				http.Error(w, err.Error(), http.StatusBadRequest)
				return
			}
			status = http.StatusConflict
		} else err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
```

2022-03-11 07:37 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +	response, err := h.storage.SaveBatchURLS(userID, request, h.config.BaseURL)
Что-то мне это не нравится. Мне кажется не стоит репозиторию знать о baseURl, посмотрю имплементацию и может поменяю мнение)

2022-03-11 07:38 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
тут может быть уместнее internalServerError

2022-03-11 07:39 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
А тут точно InternalServerError, если сервер не может заенкодить, значит проблема не в исзодных данных должна быть

2022-03-11 07:42 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusNoContent)
хммм, может ли быть это ошибкой сервера в данном случае?

2022-03-11 07:43 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
InternalServerError :)

2022-03-11 07:43 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
В таком случае тут пятисотая, а не ошибка клиента)

2022-03-11 07:46 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +	conn, err := pgx.Connect(r.Context(), h.config.DatabaseDsn)
может унесем ping в метод репозитория? Мы же можем переиспользовать соединение. К тому же лучше в пинге получать статус существующего соединения, а так мы получаем информацию что да, можно подконнектиться к БД.

2022-03-11 07:49 UTC, sergeysergeevru commented on internal/app/middleware/auth.go
> +	if cipherInstance == nil {
можно заиспользовать sync.once

2022-03-11 07:56 UTC, sergeysergeevru commented on internal/app/middleware/auth.go
> +var cipherInstance *cipherData
вот не знаю) Не нравятся мне синглтоны и все. Может такая деформация у меня на фоне DI.  Я бы предпочел создавать инстанс в AuthHandle и потом использовать в анонимной функции которую ты там возвращаешь. С другой стороны, не готов утверждать что это критически плохо. Поэтому рассматривай этот как один из возможных вариантов, не как за обязанность исправить)

2022-03-11 08:11 UTC, sergeysergeevru commented on internal/app/middleware/constants.go
> +var UserCtx UserContextType = "UserCtx"
в таком случае уместнее сделать UserCtx константой

2022-03-11 08:28 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +	row := r.conn.QueryRow(context.Background(), "SELECT COUNT(*) FROM urls")
меня смущает одна вещь: если у тебя auto increment в базе и допустит ты снесешь несколько старых записей, то ты получишь неправильный id. Допустим у тебя есть одна запись с id= 2, то ты сгенерируешь id = (count(*)+1) = 1+1 = 2. Что-то тут надо менять)

2022-03-11 08:28 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +	row := r.conn.QueryRow(context.Background(), "SELECT COUNT(*) FROM urls")
про проблему уже писал вверху)

2022-03-11 08:31 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +		response = append(response, types.ResponseBatchJSON{CorrelationID: v.CorrelationID, ShortURL: utils.MakeShortURL(baseURL, id+1)})
да, все таки мне не нравится прокидывание baseURL сюда. Такое ощущение, что генерация короткой ссылки должно быть сделано где-то выше.

2022-03-11 08:33 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +	defer tx.Rollback(ctx)
ты таким образом пытаешься сделать ролбэк всегда. Он должен исполняться при ошибке, можно сделать так: 
```
func (r *DBRepository) SaveBatchURLS(userID string, request types.RequestBatch, baseURL string) (response types.ResponseBatch, err error) {
// тут какой-то код
defer func(){
      if err != nil {
          tx.Rollback(ctx)
      }
}()
// какой-то код
}
```

2022-03-11 08:34 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +func (r *DBRepository) GetShortURLByOriginalURL(originalURL string) (int, error) {
ты получаешь ID а не shorLink здесь)

2022-03-11 08:35 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +		links = append(links, types.Link{ShortURL: utils.MakeShortURL(baseURL, id), OriginalURL: url})
здесь бы я тоже не делал генерацию короткой ссылки, а переложил ответственность на слой выше

2022-03-11 08:36 UTC, sergeysergeevru commented on internal/app/repository/db.go
> +    create unique index if not exists original_url_ix on urls(original_url);`
не плохо. Возможно в будущем надо будет поразбираться с миграциями. Если все сложится может вебинар сделаем. В текущей ситуации можно просто в константу вынести)

2022-03-11 08:37 UTC, sergeysergeevru commented on internal/app/repository/file.go
> +}
То есть новый функционал не будет работать если мы захотим использовать FileRepository?

2022-03-11 08:39 UTC, sergeysergeevru commented on internal/app/repository/inmemory.go
> +}
аналогично с FileRepository :)

2022-03-11 08:39 UTC, sergeysergeevru commented on internal/app/repository/file.go
> +			links = append(links, types.Link{ShortURL: utils.MakeShortURL(baseURL, record.ID), OriginalURL: record.OriginalURL})
уже говорил, что репозиторию лучше не решать вопрос генерации ссылки, с моей точки зрения)

2022-03-11 08:41 UTC, sergeysergeevru commented on internal/app/repository/inmemory.go
> +		links = append(links, types.Link{ShortURL: utils.MakeShortURL(baseURL, v), OriginalURL: URL})
думаю ты догадался, что тут я хочу сказать, что получается логику по генерации короткой ссылки куда-то выше унести) Пусть репозиторий будет ответственен за хранение и получения информации из хранилища

2022-03-11 08:52 UTC, sergeysergeevru requested changes
Привет! Все очень гуд. Очень понравилось, что использовал транзакции. Хочу предложить чуток доработать: не перекладывать ответственность за генерацию короткой ссылки на репозиторий, убрать дупликацию кода, может быть улучшить твой метод ping, а так же улучшить работу с autoincrement, так как сейчас при удалении какой-нибудь записи можем получить неправильную генерацию id. Однако большое спасибо, что прислал работу достаточно быстро от начала 3 спринта, я думаю у нас есть время ее чуток улучшить!

2022-03-12 20:34 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +	userID := ctx.(string)
Пофиксил, надеюсь теперь ок)

2022-03-12 20:35 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
>  	shortURL := utils.MakeShortURL(h.config.BaseURL, id)
Вынес в отдельную функцию проверку ошибки UniqueViolation от БД.

2022-03-12 20:35 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
>  	shortURL := utils.MakeShortURL(h.config.BaseURL, id)
Исправил)

2022-03-12 20:37 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +			http.Error(w, err.Error(), http.StatusBadRequest)
Исправил

2022-03-12 20:37 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +	response, err := h.storage.SaveBatchURLS(userID, request, h.config.BaseURL)
Исправил)

2022-03-12 20:38 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Исправил

2022-03-12 20:38 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Исправил

2022-03-12 20:42 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +		w.WriteHeader(http.StatusNoContent)
Исправил

2022-03-12 20:42 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Исправил :)

2022-03-12 20:42 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +		http.Error(w, err.Error(), http.StatusBadRequest)
Исправил)

2022-03-12 20:43 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +	conn, err := pgx.Connect(r.Context(), h.config.DatabaseDsn)
Сделал методом репозитория, получаю статус текущего соединения

2022-03-12 20:44 UTC, vstebletsov89 commented on internal/app/middleware/auth.go
> +	if cipherInstance == nil {
Использовал sync.once, надеюсь нормально получилось :)

2022-03-12 20:45 UTC, vstebletsov89 commented on internal/app/middleware/constants.go
> +var UserCtx UserContextType = "UserCtx"
Сделано

2022-03-12 20:50 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +	row := r.conn.QueryRow(context.Background(), "SELECT COUNT(*) FROM urls")
Переделал генерацию ID короткой ссылки. Теперь использую функцию рандома, которая генерирует рандомный массив байт из букв и цифр. Это теперь общая функция, которая используется для шифрования пользователя во время авторизации и генерации ID короткой ссылки.

2022-03-12 20:51 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +	row := r.conn.QueryRow(context.Background(), "SELECT COUNT(*) FROM urls")
Пофиксил)

2022-03-12 20:52 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +		response = append(response, types.ResponseBatchJSON{CorrelationID: v.CorrelationID, ShortURL: utils.MakeShortURL(baseURL, id+1)})
Исправил

2022-03-12 20:52 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +	defer tx.Rollback(ctx)
Исправил

2022-03-12 20:52 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +func (r *DBRepository) GetShortURLByOriginalURL(originalURL string) (int, error) {
Исправил)

2022-03-12 20:53 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +		links = append(links, types.Link{ShortURL: utils.MakeShortURL(baseURL, id), OriginalURL: url})
Исправил

2022-03-12 20:53 UTC, vstebletsov89 commented on internal/app/repository/db.go
> +    create unique index if not exists original_url_ix on urls(original_url);`
Исправил

2022-03-12 20:53 UTC, vstebletsov89 commented on internal/app/repository/file.go
> +}
Исправил

2022-03-12 20:54 UTC, vstebletsov89 commented on internal/app/repository/inmemory.go
> +}
Исправил

2022-03-12 20:54 UTC, vstebletsov89 commented on internal/app/repository/file.go
> +			links = append(links, types.Link{ShortURL: utils.MakeShortURL(baseURL, record.ID), OriginalURL: record.OriginalURL})
Согласен, сейчас код выглядит лучше :) Исправил

2022-03-12 20:55 UTC, vstebletsov89 commented on internal/app/repository/inmemory.go
> +		links = append(links, types.Link{ShortURL: utils.MakeShortURL(baseURL, v), OriginalURL: URL})
Исправил

2022-03-12 23:00 UTC, sergeysergeevru commented on internal/app/utils/utils.go
> +	rand.Seed(time.Now().UnixNano())
сидить math rand стоит единожды за время работы программы, иначе у тебя не получится распределение псевдослучайной величины равномерной

2022-03-12 23:02 UTC, sergeysergeevru commented on internal/app/utils/constants.go
> +)
Риторический вопрос: стоит ли вообще так дробить константы отдельно, имплементация отдельно?)

2022-03-12 23:04 UTC, sergeysergeevru commented on internal/app/utils/utils.go
>  import (
тоже риторическая мысль, вообще utils это настолько абстрактная вещь. Может к такому названию пакета стоит прибегать в исключительных случаях. Если у тебя методы используются только в одном пакете, то может стоит его там и оставить?)

2022-03-12 23:14 UTC, sergeysergeevru commented on internal/app/repository/inmemory.go
>  }
я правильно понимаю ты не сохраняешь список ссылок в хранилище?

2022-03-12 23:15 UTC, sergeysergeevru commented on internal/app/repository/file.go
>  }
здесь тоже получается ты тоже не положишь в файл данные)

2022-03-12 23:24 UTC, sergeysergeevru approved these changes
Добро) Я думаю как результат 3 спринта хорошо. Учти (можешь глянуть документацию) про вызов rand.Seed. Там еще получается у тебя имплементация inmemory и FileRepository с точки зрения bulk insert не сохраняют записи. Однако, я чуток поразмыслил по этому поводу и решил не докапываться. Все таки это задание в первую очередь направлено было на получение навыков работы с базой. Поэтому вообще не хочется заставлять делать бессмысленную работу) Однако если захочешь что-то поправить и чтобы я проверил, сделай правки в рамках следующего спринта. А сейчас аппрув) Успехов в следующем спринте! спасибо)

2022-03-14 11:16 UTC, merged