Increment 17
vstebletsov89/go-developer-course-shortener pull request #17
Opened 2022-10-19 17:47 UTC by vstebletsov89

2022-10-21 16:45 UTC, bambruysk requested changes

2022-10-21 16:45 UTC, bambruysk commented on internal/app/handlers/example_test.go
> +	req, _ := http.NewRequest(method, ts.URL+path, body)
почему в этом методе игнорируются ошибки - если это тест то используйте asset.NoError(t, err)

2022-10-21 16:45 UTC, bambruysk commented on internal/app/handlers/example_test.go
> +	"encoding/json"
Нужно отсортировать импорты

2022-10-21 16:45 UTC, bambruysk commented on internal/app/handlers/example_test.go
> +	respBody, _ := ioutil.ReadAll(resp.Body)
ioutil Deprecated - нужно использоват io

2022-10-21 16:45 UTC, bambruysk commented on internal/app/handlers/handlers_test.go
> +		defer resp.Body.Close()
defer в цикле не хорошо вызывать, можно вызвать его явно или после цикла - иначе образуется огромная пачка деферов которые тормозят

2022-10-22 11:04 UTC, vstebletsov89 commented on internal/app/handlers/example_test.go
> +	req, _ := http.NewRequest(method, ts.URL+path, body)
исправил. это не совсем тест, этот код используется только для примеров.

2022-10-22 11:05 UTC, vstebletsov89 commented on internal/app/handlers/example_test.go
> +	"encoding/json"
отсортировал утилитой goimports

2022-10-22 11:05 UTC, vstebletsov89 commented on internal/app/handlers/example_test.go
> +	respBody, _ := ioutil.ReadAll(resp.Body)
исправил везде

2022-10-22 11:06 UTC, vstebletsov89 commented on internal/app/handlers/handlers_test.go
> +		defer resp.Body.Close()
понятно, исправил на явный вызов без defer здесь и во всех похожих местах

2022-10-25 14:14 UTC, bambruysk approved these changes
Принято

2022-10-25 18:38 UTC, merged