Increment 22
vstebletsov89/go-developer-course-shortener pull request #22
Opened 2022-11-13 19:40 UTC by vstebletsov89

2022-11-14 16:37 UTC, bambruysk requested changes
нужно поправить Graceful shutdown

2022-11-14 16:37 UTC, bambruysk commented on internal/worker/worker.go
> +						defer wg.Done()
если есть wg. то где то должен быть wg.Wait 

Если у нас положим канал набит входными джобами то они могут не успеть обработаться к моменту завершения программы. В итоге проблема милосердного завершения остается.  

Лучше придерживаться такой стратегии. завершаем текущую таску, и на этом все выходим из цикла.

2022-11-14 16:37 UTC, bambruysk commented on internal/configs/env_test.go
> +				err = os.WriteFile(file, cfg, 0666)
лучше использовать t.SetEnv()

2022-11-15 12:55 UTC, vstebletsov89 commented on internal/configs/env_test.go
> +				err = os.WriteFile(file, cfg, 0666)
Исправил.

2022-11-15 12:58 UTC, vstebletsov89 commented on internal/worker/worker.go
> +						defer wg.Done()
Спасибо за развернутый комментарий! Исправил код, добавил wg.Wait и новую функцию для закрытия входного канала, чтобы выходить из цикла после закрытия канала в случае graceful shutdown.

2022-11-18 08:05 UTC, bambruysk approved these changes
Принято

2022-11-18 08:05 UTC, bambruysk commented on internal/worker/worker.go
> +			for v := range p.inputCh {
Вот тут все таки сложный момент . Обычно при завершении приложения придет sigint - затем через некоторый таймаут придет sigkill  - который убьет процесс, если мы уверены что все запросы из этого канала успеют завершиться в базе, то ок. Если нет, то лучше просто выйти и потерять эти данные. Иначе и данные потеряются и в базе подвиснет транзакция например.  Вот тут тонкий момент в общем

2022-11-21 11:57 UTC, merged