Increment 7
vstebletsov89/go-developer-course-shortener pull request #7
Opened 2022-02-20 11:32 UTC by vstebletsov89

Инкременты на проверку с четвертого по седьмой.

2022-02-22 19:08 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +	if fileStoragePath != configs.FileStorageDefault {
ну нее, давай не будем так) Когда у тебя третье хранилище появится, то ты еще один if сюда пропишешь?) может полиморфизм применим? Давай у нас будет два разных репозитория, которые подходят под один интерфейс? Одна имплементация для inmemory, другая будет для хранения в файлах. Тогда добавлять 3,4,5 etc хранилище будет очень просто) да и тесты пилить проще: больше контроля, можно мокать)

2022-02-22 19:18 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +	encoder.Encode(response)
Давай ошибку енкодинга проверим, по братски)

2022-02-22 19:21 UTC, sergeysergeevru commented on internal/app/handlers/handlers_test.go
> +	config := configs.ReadConfig()
я бы посоветовал конструировать конфиг в тестах руками, с моей точки зрения так гораздо больше контроля.

2022-02-22 19:28 UTC, sergeysergeevru commented on internal/configs/env.go
> +}
вот это костыль какой-то. Я помню что видел сообщение что у кого-то тесты падали. Я так понимаю тесты падали, потому что ты читаешь флаги во время своих тестов. Луше такое не делать во время тестирования: лучше задать руками конфиг на тестах, иначе, как уже заметил тесты могут завалиться)

2022-02-22 19:29 UTC, sergeysergeevru commented on internal/configs/env.go
> +		log.Fatal(err)
давай лучше кинем ошибку выше, пусть тот кто вызывает метод и обрабатывает ее) И решает завершать программу или еще не стоит

2022-02-22 19:31 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +				log.Fatal(err)
log.fatal под капотом имеет инструкцию os.Exit(1), мы точно должны уполномачивать репозиторий завершать программу? давай ошибки выше на слой передавать, а там может клиенту отдавать сообщение?

2022-02-22 19:32 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +	}
разделим на два разных репозитория и избавимся тогда от лишнего ветвления)

2022-02-22 19:33 UTC, sergeysergeevru commented on internal/app/handlers/handlers_test.go
> +	r.Get("/{ID}", handler.HandlerGET)
а вот это хорошо обыграл,  претензий нет)

2022-02-22 19:34 UTC, sergeysergeevru commented on internal/app/handlers/handlers_test.go
> +		log.Fatal(err)
может asser.NoError вызовем или как там пишется не помню без IDE?

2022-02-22 19:37 UTC, sergeysergeevru commented on internal/app/handlers/handlers_test.go
> +		log.Fatal(err)
аналогично вышесказанному)

2022-02-22 19:38 UTC, sergeysergeevru commented on internal/app/handlers/handlers_test.go
> +	}
assert.NoError

2022-02-22 19:44 UTC, sergeysergeevru requested changes
Гуд поделил на слои и использовал DI. Однако давай переделывать работу с repository. Давай разделять inmemory и file repository и решать какой использовать когда готовим приложение к запуску. Не стал сильно глубоко ревьюить текущий репозиторий и тесты, потому что создание двух разных хранилищ должно потянуть изменения и там и сям. Конфиг для тестов можно руками прописывать, я бы не советовал использовать переменные окружения, так больше контроля должно получиться.

2022-02-23 13:39 UTC, vstebletsov89 commented on internal/app/repository/repository.go
> +	if fileStoragePath != configs.FileStorageDefault {
Согласен) исправил это дело, сделал два разных репозитория `FileRepository` и `InMemoryRepository` которые реализуют общий интерфейс `Repository`.

2022-02-23 13:40 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +	encoder.Encode(response)
Пофиксил)

2022-02-23 13:43 UTC, vstebletsov89 commented on internal/app/handlers/handlers_test.go
> +	config := configs.ReadConfig()
Согласен, так намного удобнее. Конструирую конфиг теперь в каждом тесте отдельно без переменных окружения и флагов.

2022-02-23 13:46 UTC, vstebletsov89 commented on internal/configs/env.go
> +}
Удалил этот костыль. Ты был прав, после того как убрал чтение флагов из тестов, проблема с переопределением флагов ушла.

2022-02-23 13:47 UTC, vstebletsov89 commented on internal/configs/env.go
> +		log.Fatal(err)
Пофиксил.

2022-02-23 13:49 UTC, vstebletsov89 commented on internal/app/repository/repository.go
> +				log.Fatal(err)
Пофиксил.

2022-02-23 13:49 UTC, vstebletsov89 commented on internal/app/repository/repository.go
> +	}
Да, теперь код выглядит намного лучше)

2022-02-23 13:51 UTC, vstebletsov89 commented on internal/app/handlers/handlers_test.go
> +		log.Fatal(err)
Пофиксил.

2022-02-23 13:51 UTC, vstebletsov89 commented on internal/app/handlers/handlers_test.go
> +		log.Fatal(err)
Пофиксил)

2022-02-23 13:51 UTC, vstebletsov89 commented on internal/app/handlers/handlers_test.go
> +	}
Пофиксил.

2022-02-23 14:38 UTC, sergeysergeevru commented on internal/configs/env.go
> +	FileStoragePath string `env:"FILE_STORAGE_PATH" envDefault:"FILE_STORAGE_PATH_NOT_DEFINED"`
наверное дело вкуса, но можно просто по дефолту оставлять пустой строкой. И уже от этого плясать, если у тебя **не пустая строка** в FileStoragePath то тогда инициализуем FileRepository.

2022-02-23 14:39 UTC, sergeysergeevru commented on internal/configs/env.go
> +	FileStoragePath string `env:"FILE_STORAGE_PATH" envDefault:"FILE_STORAGE_PATH_NOT_DEFINED"`
Мне просто кажется, что пустая строка гораздо логичнее (я бы сказал natural) чем какая-то специфичная константа.

2022-02-23 14:40 UTC, sergeysergeevru commented on internal/configs/constants.go
> +	ContentValueJSON      = "application/json"
Это не относится к конфигу, давай унесем к хендлерам если ты там это используешь(

2022-02-23 14:44 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +	return shortURL, nil
вынести общую логику в отдельную функцию хорошая идея, но есть но. Ты унес это в пакет репозитория, что по природе не сильно вяжется с репозиторием. Ответственность репозитория это положить в хранилище и извлечь информацию, здесь же у тебя есть валидация, которую стоит где-нибудь на уровне хендлера делать. Можешь спец функцию для валидации сделать.

2022-02-23 14:45 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +	}
если у тебя пустая строка, то на сколько помню url.Parse отдаст ошибку и до этой проверки не дойдет

2022-02-23 14:51 UTC, sergeysergeevru commented on internal/app/repository/inmemory.go
> +	id, err := r.getNextID()
Мне не очень нравится идея с генерацией ключа на уровне репозитория (что здесь, что в. FileRepository). Я бы предпочел генерировать на уровне выше. Хотя тут понятно, что твой подход чем то напоминает. Autoincrement в реляционных базах данных. Предлагаю поступить сейчас так: давай оставим, а когда тебе это действительно начнет усложнять жизнь (может такое и не произойти), то уже подумаем как лучше. Не хочу заставлять переделывать, только из-за своей чуйки, так как хороших аргументов пока нет)

2022-02-23 14:55 UTC, sergeysergeevru commented on internal/app/repository/file.go
> +	return file, nil
Можно так) Есть вообще вопрос а стоит ли os.OpenFile в отдельную функцию оборачивать. 
```suggestion
	return os.OpenFile(fileName, flag, 0777)
```

2022-02-23 15:05 UTC, sergeysergeevru commented on internal/app/handlers/handlers.go
> +	shortURL, err := repository.SaveShortURL(h.storage, string(body), h.config.BaseURL)
как я говорил в репозитори, так не оч. У тебя должно примерно так выглядеть здесь, если не обернешь в какой-нибудь app слой. 
```
shortURL, err := h.storage. SaveURL(longUrl). 
```
Давай все таки не смешивать зоны отвественности

2022-02-23 15:06 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +	getNextID() (int, error)
Интерфейс это контракт описывающий какие есть публичные методы у объекта. Приватные методы здесь бессмысленны

2022-02-23 15:07 UTC, sergeysergeevru commented on internal/app/repository/repository.go
> +type Repository interface {
вообще так как у Го утиная типизация, можно описывать интерфейс в месте его использования. Так как структуре не знает какой интерфейс(ы) она имплеменитрует. Не критично, просто ремарка, как еще можно)

2022-02-23 15:12 UTC, sergeysergeevru requested changes
Давай все-таки снимем ответственность с репозитория за валидацию и возможно за генерацию ссылки. Репозиторий должен отвечать только за хранение. Остальное просто рекомендации. Разберемся с репозиторием до конца и будет вообще гуд!)

2022-02-23 17:04 UTC, vstebletsov89 commented on internal/configs/env.go
> +	FileStoragePath string `env:"FILE_STORAGE_PATH" envDefault:"FILE_STORAGE_PATH_NOT_DEFINED"`
Пофиксил.

2022-02-23 17:04 UTC, vstebletsov89 commented on internal/configs/constants.go
> +	ContentValueJSON      = "application/json"
Пофиксил.

2022-02-23 17:05 UTC, vstebletsov89 commented on internal/app/repository/repository.go
> +	return shortURL, nil
Переделал, сделал отдельные функции для валидаци и создания короткой ссылки.

2022-02-23 17:07 UTC, vstebletsov89 commented on internal/app/repository/repository.go
> +	}
Если я удаляю эту проверку, то почему-то падает юнит тест, который передает пустой URL, выглядит как будто url.Parse не отдает ошибку в этом случае.

2022-02-23 17:08 UTC, vstebletsov89 commented on internal/app/repository/file.go
> +	return file, nil
Удалил общую функцию, похоже действительно в ней нет смысла.

2022-02-23 17:08 UTC, vstebletsov89 commented on internal/app/handlers/handlers.go
> +	shortURL, err := repository.SaveShortURL(h.storage, string(body), h.config.BaseURL)
Пофиксил.

2022-02-23 17:08 UTC, vstebletsov89 commented on internal/app/repository/repository.go
> +	getNextID() (int, error)
Пофиксил.

2022-02-23 17:10 UTC, sergeysergeevru approved these changes
Не сказал бы что пакет utils тебе сильно нужен был (можно было просто отдельными функциями в пакете с хэндлерами оставить), но если очень хочется унести эту логику из хэндлера, то ладо :) Вообще все гуд! Аппрув)

2022-02-24 08:41 UTC, merged